preset: recommended

risky: true

linting: true

finder:
  exclude:
    - vendor
    - build

enabled:
  - align_equals
  - combine_consecutive_unsets
  - concat_with_spaces
  - const_visibility_required
  - declare_strict_types
  - dir_constant
  - ereg_to_preg
  - mb_str_functions
  - modernize_types_casting
  - no_blank_lines_after_return
  - no_blank_lines_before_namespace
  - no_empty_comment
  - no_useless_else
  - ordered_class_elements
  - php_unit_construct
  - php_unit_dedicate_assert
  - phpdoc_add_missing_param_annotation
  - pow_to_exponentiation
  - protected_to_private
  - random_api_migration
  - return_type_declaration
  - not_operator_with_successor_space

disabled:
  - blank_line_after_opening_tag
  - unalign_equals
  - self_accessor
  - concat_without_spaces
  - single_blank_line_before_namespace
  - simplified_null_return

finder:
  exclude:
    - "build"
    - "vendor"
    - "tests"
  name:
    - "*.php"
