# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "normalize composer.json"

on: # yamllint disable-line rule:truthy
    push:
        paths:
            - "composer.json"

jobs:
    normalize:
        timeout-minutes: 1

        runs-on: "ubuntu-latest"

        steps:
            - name: "Git checkout"
              uses: "actions/checkout@v2"
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Validate Composer configuration"
              run: "composer validate --strict"

            - name: "Normalize composer.json"
              run: |
                  composer global require ergebnis/composer-normalize
                  composer normalize --indent-style=space --indent-size=4 --no-check-lock --no-update-lock --no-interaction --ansi

            - uses: "stefanzweifel/git-auto-commit-action@v4.15.4"
              with:
                  commit_message: "chore: normalize composer.json"
